### ISSUE TITLE
Working towards merging `singledesign` into `main`

### ISSUE THREAD

**Issue by smishr** [xKDR/Survey.jl#165]
We should work backwards from things needed to be done to merge `singledesign` into `main`. I propose the atleast the checklist below. Feel free to comment and add things to do.

- [ ] Everything in milestone 0.3.0 release
- [x] #178 
- [x] #179 
- [x] #156 
- [x] @iuliadmtru is currently working on #177 to improve documentation (both the docstrings and the files inside `docs/src`). Another separate PR on documentation may be done later. 
- [x] The README is outdated. #176
- [x] Bootstrap working for arbitrary statistic function using `SurveyDesign` and `ReplicateDesign` #138 
- [x] Precompiling the package gives a warning because `quantile` is defined twice. That is mentioned in issue #171 and will be fixed by PR #172.
- [x] #138 
- [x] Resolve #129 
- [x] Debug #161 and make new PR @ayushpatnaikgit 
- [x] The `show` methods for `SurveyDesign` and `ReplicateDesign` could be greatly improved. This will mean changing the doctests again.
